### ISSUE TITLE
compilation failed on ubuntu

### ISSUE THREAD

**Issue by goodthebest** [haven-protocol-org/haven-wallet-backend#1]
I've tried to run this compilation script on three ubuntu OS 16.04, 18.04 and 20.04 and on all I end up getting this error. Could you suggest me how to get haven daemon on ubuntu 

`Openmonero tree not found in /root/haven-wallet-backend - cloning from github...
Cloning into 'openmonero'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 11056 (delta 3), reused 1 (delta 0), pack-reused 11049
Receiving objects: 100% (11056/11056), 20.13 MiB | 1.59 MiB/s, done.
Resolving deltas: 100% (6442/6442), done.
Submodule 'src/xmregcore' (https://github.com/moneroexamples/xmregcore) registered for path 'src/xmregcore'
Cloning into '/root/haven-wallet-backend/openmonero/src/xmregcore'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 669 (delta 2), reused 4 (delta 2), pack-reused 659
Receiving objects: 100% (669/669), 2.62 MiB | 5.19 MiB/s, done.
Resolving deltas: 100% (478/478), done.
Submodule path 'src/xmregcore': checked out 'be50c5257897e2a0d610317056a149f07ec894f6'
Submodule 'ext/googletest' (https://github.com/abseil/googletest) registered for path 'src/xmregcore/ext/googletest'
Cloning into '/root/haven-wallet-backend/openmonero/src/xmregcore/ext/googletest'...
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 21360 (delta 13), reused 16 (delta 5), pack-reused 21326
Receiving objects: 100% (21360/21360), 8.09 MiB | 10.97 MiB/s, done.
Resolving deltas: 100% (15808/15808), done.
Submodule path 'src/xmregcore/ext/googletest': checked out '3f5b5b8f8493a03fa25f1e4a7eae7678514a431d'
Branch 'master' set up to track remote branch 'master' from 'origin'.
fatal: A branch named 'master' already exists.
HEAD is now at de1f01e Merge pull request #173 from moneroexamples/devel
Already up to date.
Applying patches to Openmonero codebase:
        patching file /root/haven-wallet-backend/openmonero/sql/openmonero.sql
        patching file /root/haven-wallet-backend/openmonero/sql/openmonero_test.sql
        patching file /root/haven-wallet-backend/openmonero/src/xmregcore/src/monero_headers.h
        patching file /root/haven-wallet-backend/openmonero/src/xmregcore/cmake/FindMonero.cmake
Hunk #1 FAILED at 31.
Hunk #2 FAILED at 82.
2 out of 2 hunks FAILED -- saving rejects to file /root/haven-wallet-backend/openmonero/src/xmregcore/cmake/FindMonero.cmake.rej
        patching file /root/haven-wallet-backend/openmonero/src/TxSearch.cpp
        patching file /root/haven-wallet-backend/openmonero/src/utils.cpp
Compiling patched openmonero code...
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found MySQL++: /usr/include/mysql++;/usr/include/mysql, /usr/lib/x86_64-linux-gnu/libmysqlpp.so;/usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Found Restbed include at:
    /root/haven-wallet-backend/openmonero/ext/restbed
-- Configuring directory /root/haven-wallet-backend/openmonero/build/config
-- Configuring file config.json
-- MONERO_DIR: ~/haven-offshore/monero
-- Trying different folder for monero libraries
CMake Error at src/xmregcore/cmake/FindMonero.cmake:55 (message):
  Monero libraries not found in:
  /root/haven-offshore/monero/build/Linux/master/release
Call Stack (most recent call first):
  src/xmregcore/CMakeLists.txt:18 (find_package)

-- Configuring incomplete, errors occurred!
See also "/root/haven-wallet-backend/openmonero/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
Done.
`

**Comment by MartyHav** [comment]
repository is deprecated.
You can find the related README here: https://github.com/haven-protocol-org/havenwallet-backend

**Comment by goodthebest** [comment]
@MartyHav I've used this repo  https://github.com/haven-protocol-org/havenwallet-backend and getting this error running **cmake -DMONERO_DIR=~/havenwallet-backend ..**

![image](https://user-images.githubusercontent.com/1715740/101767920-bce68a80-3b06-11eb-8108-316c574c7f4d.png)

**Comment by MartyHav** [comment]
Do you have a particular reason to get it run? I think we will delete it soon, it won't work with havens offshore feature.
As I can remember DMONERO_DIR should point to Monero. 
Really curious why you like to get it run. I you want to get in touch, stop by at https://discordapp.com/invite/CCtNxfG

**Comment by goodthebest** [comment]
@MartyHav I am setting up Haven pool for that I need a daemon to run. Could you please guide me how to achieve it to run a pool?

**Comment by goshiz** [comment]
Hi, please come by the discord. Github issues are not there for that.
